# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jensravens.de" # the base hostname & protocol for your site
twitter_username: swiftberlin
github_username:  jensravens
port: 3000
excerpt_separator: <!--more-->

permalink: :title/

# Build settings
# markdown: kramdown
markdown: redcarpet

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
      class: 'page'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      class: 'post'
